name: Build and Deploy to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        env:
          REPOSITORY: ${{ github.repository }}
        run: ./bin/docker-build.sh

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository }}/spring-boot-application:latest